apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ak30wxhdw-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ak30wxhdw-java-quarkus-gitops